name: Update Table of Contents

on:
  push:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run TOC Update Script
        run: |
          python update_toc.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'rcode'
          git config --global user.email 'rgonzo1355@gmail.com'
          git add -u
          git commit -m "Automatically update TOC" || echo "No changes to commit"
          git push

